/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_current_time                   21
#define gattdb_local_time_information         24
#define gattdb_reference_time_information     26
#define gattdb_my_character                   29
#define gattdb_my_notif                       31
#define gattdb_ota_control                    35


#endif // __GATT_DB_H
